{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.frontend.service.annotations }}
  annotations:
{{ toYaml .Values.frontend.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "dvof.frontend.fullname" . }}
  labels:
    {{- include "dvof.frontend.labels" . | nindent 4 }}
    service: frontend
{{ include "dvof.namespace" . | indent 2 }}
spec:
  ports:
  - port: {{ .Values.frontend.service.servicePort }}
    name: http
  selector:
    {{- include "dvof.frontend.matchLabels" . | nindent 4 }}
{{- end }}
