---
{{- if .Values.openstackmgr.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dvof.openstackmgr.fullname" . }}
  labels:
    {{- include "dvof.openstackmgr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openstackmgr.replicaCount }}
  selector:
    matchLabels:
      {{- include "dvof.openstackmgr.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dvof.openstackmgr.labels" . | nindent 8 }}
        {{- if .Values.openstackmgr.podLabels}}
        {{ toYaml .Values.openstackmgr.podLabels | nindent 8 }}
        {{- end}}
    spec:
      containers:
      - name: {{ template "dvof.name" . }}-{{ .Values.openstackmgr.name }}
        image: "{{ .Values.openstackmgr.image.repository }}:{{ .Values.openstackmgr.image.tag }}"
        imagePullPolicy: "{{ .Values.openstackmgr.image.pullPolicy }}"
        command: ["./openstackmgr"]
        #args: ["-loglevel DEBUG" ,"-openstackmgrIP 192.168.121.127", "-edgeAppImage app_video_play.tar", "-dcAppImage downstream_video_v3"]
        args:
               - "-loglevel=DEBUG"
        ports:
        - containerPort: 8085
{{- end }}


