{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dvof.serviceAccountName" . }}
  labels:
{{ include "dvof.labels" . | indent 4 }}
{{- end -}}
